title: Karla Ximena López García
logo: https://github.com/karlalopgar08-code/karla08#:~:text=2%20Commits-,1749672707801.jpeg,-foto
description: Inteligencia de Negocios │ Innovacion y Transformación Digital │ Administración Estratégica del Comercio Detallista Omnicanal │ Análisis y Manipulación de Datos │ Dashboards
show_downloads: true
theme: jekyll-theme-minimal
